
name: deploy gh-pages

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          yarn install
      - name: build docs
        run: |
          yarn docs:build
      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vuepress/dist

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Publish to GitHub Pages 🚀
          id: deployment
          uses: actions/deploy-pages@v4

